### ISSUE TITLE
JPEG screenshots require multiple-of-4 video dimensions

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#144]
@jar3817 @maci0 I think we've seen this before. Would one of you be able to look into it? I'm not sure if the 64 bit Windows build is affected.

![quetoo001](https://cloud.githubusercontent.com/assets/643118/16995086/5acde46c-4e78-11e6-9ea5-e2ad38cbdecc.jpg)

If this is going to be a huge pain in the ass, I'd welcome a patch that gives us PNG screenshots, so that we can drop libjpeg entirely. Just food for thought.

**Comment by jdolan** [comment]
CC @Panjoo

**Comment by WickedShell** [comment]
That's byte alignment error on glReadPixels (last time I fixed it was a
format that wasn't specified causing the alpha byte to bed ignored one way
or the other). I'd recommend STB image as a libjpeg replacement

**Comment by jdolan** [comment]
Hot damn, `stb_image_write.h` looks awesome.

**Comment by jdolan** [comment]
Still, having looked at `Img_WriteJPEG`, I don't see how we're going wrong.

@Panjoo, I did a `make clean` on the i686 build on Jenkins and re-ran it. There's a chance that it had picked up the wrong version of libjpeg or something. Would you mind running the updater and confirming if this issue persists?

**Comment by WickedShell** [comment]
What were the dimensions of the image? It's a bit hard to see on a phone...
I'm guessing it's not a multiple of 4 in width...

**Comment by Panjoo** [comment]
Oh crap, my bad:/.  Jay, I ran your latest update but that didn't fix it because the problem wasn't in libjpeg but between the chair and keyboard. So it's safe to just close this.
> I'm guessing it's not a multiple of 4 in width..

Using the ingame Video options all I see is 'mode: custom' with nothing else to choose from or see what it's currently set to. [-> custom-res](http://panjoo.tastyspleen.net/quetoo/uploaded/custom-res.jpg)
After updating a bunch of times while checking for bugs I decided to get rid of my old quetoo.cfg. My monitors native width is "1366".... so you were right, after I changed it back in the .cfg to 1360 it's all good again.

**Comment by jdolan** [comment]
Thanks for providing the answer, @WickedShell! I think we can demote this to a minor bug and back it out of the 1.0 Milestone. We should eventually try to support arbitrary sized screenshots..

**Comment by WickedShell** [comment]
This is a regression in that I used to have it working for odd sized
screenshots

**Comment by jdolan** [comment]
Interesting. Viewing the `git blame` for `Img_WriteJPEG` and `R_Screenshot_f` doesn't reveal anything of note.

**Comment by WickedShell** [comment]
Was a problem with not having declared the buffer format somewhere along
the way last time.a quick search of the old svn history doesn't find it for
me though...

**Comment by WickedShell** [comment]
Try setting the unpack alignment prior to reading the pixels back: IE prior to https://github.com/jdolan/quetoo/blob/a5a28927d121369a870f8fe0e58b671d8273840f/src/client/renderer/r_image.c#L95 we should have set the glPixelStorei(GL_UNPACK_ALIGNMENT, 1)

Default value is 4, which is why it works if your screen is a power of 4. I had to do this before as without setting the unpack alignment we would inadvertenly write past the end of the malloc'd buffer and it used to crash my Linux system.

**Comment by WickedShell** [comment]
Was pixel packing again, instead of putting the setup code out in init on start up I left it in the screenshot function, since

A) that's where we need it
B) last time I put it elsewhere it was somehow deleted afterwards, so I'm trying to tightly associate why it was needed.

**Comment by jdolan** [comment]
💯
