### ISSUE TITLE
Blend regressions in moving materials to common

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#316]
The jump pads on Aerowalk look like this before 7b729c42c19b800c06ac45dc47010cdd6d0b5f45:

![quetoo049](https://cloud.githubusercontent.com/assets/643118/21584083/6d28170a-d068-11e6-9195-da491a8c5030.jpg)

And this after:

![quetoo048](https://cloud.githubusercontent.com/assets/643118/21584084/6eecc2a2-d068-11e6-8c01-7c985ca084fb.jpg)

I *think* this is something like not setting the correct `GL_BLEND` params but I'm not sure.

CC @Panjoo

**Comment by jdolan** [comment]
Just to clarify, it may not have been that exact commit -- but I can't [easily] run that commit, or the few immediately after it, until 526b355f594c606003fd609e637634d5174cba6f when the Autotools build was fixed. So there are 3-4 commits there that I could not bisect.

**Comment by jdolan** [comment]
@Paril fixed this -- all set @Panjoo  :)

**Comment by Panjoo** [comment]
The blends seem back to normal (\o/) but the lighting looks different. The first thing I noticed upon loading a map was that the blaster looked so dark. See the ammo and playermodel in these screenshots, it's almost as if they aren't being lit correctly:

![darkentity1](https://cloud.githubusercontent.com/assets/10857572/21622878/00f741ac-d200-11e6-8944-4628590f042e.jpg)
![darkentity2](https://cloud.githubusercontent.com/assets/10857572/21622880/044c3f56-d200-11e6-9e21-a4f6fc2f8bbf.jpg)

**Comment by jdolan** [comment]
I removed a color normalization that basically boosted the ambient lighting color of the map as the baseline for all mesh model colors. This made it impossible for a mesh model to ever look truly dark. It looked really bad on the new Torn Glory and Darker Zone.

Now, I guess one could make the argument that they're often too dark. I dunno. Maybe something in the middle is best. But what you see now is not incorrect -- it's technically more correct. When objects are not within range of a light source, they receive only the ambient light of the level. Those objects appear dark because they are not within range of a light source.

**Comment by Panjoo** [comment]
Okay could be, but I don't think it looks more natural this way because it immediately felt not right to me.:/
And I believe I have an eye for these things if I say so myself.
Especially on a map like aerowalk where there is a good amount of skylight. In that screenshot the player should not only receive the amb value but also some of the sky light, right?
Many players actually like it if the entities have some more brightnes (that's why people use very high gl_modulate settings in Q2) to make them better visible, but with this change some of the items feel more out of place even though it is technically more correct.

**Comment by Paril** [comment]
In Q2, there was a MINLIGHT thing and items always had more brightness so they stood out from the map. Maybe we can do the same. Players can stay dark - using darkness is a tactic - but the items should be nice and easy to see.

Do you get any .dmp files I can look at?

**Comment by Panjoo** [comment]
I haven't re-updated yet but I tried again with lavatomb and created a .dmp file ..\AppData\Local\Temp\quetoo.DMP ...but it is apparently 247MB large. Oops.
After zip/rar-ing it's 45MB but max attach size here is 25MB. I uploaded it here-> [win7quetoo-dmp](http://panjoo.tastyspleen.net/downloads/temp/win7quetoo-dmp.rar)

The game crashes when I see 'loading faces' @ 28% each time. It also does this on Gehenna at the exact same loading stage, but then the game just plops to desktop.
The frapipe crash: I loaded Edge and was gibbing some bodies (nice bloodstains btw), and just as on fragpipe when I tried to gib a dead body with the hyper it just goes to desktop. No messages.
I guess I'll try to re-update and report back, but I don't have time right now so this will have to wait till tonight.

**Comment by jdolan** [comment]
@Panjoo `lightmap_scale` was refactored to actually *be* a scale, and not a divisor. So maps that had `lightmap_scale 8` are causing crashes now (should be `lightmap_scale 0.125` or just plain removed, which I believe was your preference). 

I tried to catch all of them, but I missed Lava Tomb. It's been fixed as of moments ago. Gehenna and others are also fixed -- you should pull `quetoo-data` to receive the fixes.

I'll see if I can reproduce your crash on Frag Pipe. Let's open a new ticket for that one, tho..

**Comment by Panjoo** [comment]
Ok I see, lavatomb is fine again but gehenna still crashes the same on loading. Game hangs for a while then closes by itself.

**Comment by jdolan** [comment]
Hah, I'm a donkey. I forgot to push the updated Gehenna ;) Incoming!
